### ISSUE TITLE
Community building?

### ISSUE THREAD

**Issue by KlavsKlavsen** [chadweimer/gomp#276]
Hi,

I was searching for a meal planner for my family, and figured this was such a huge need for everyone - so surely something Open Source should have tackled this issue... Unfortunately I've found 10k+ open source apps.. all dead and half-finished (to meet my needs atleast).. :(

So its obviously not so easy to get something that survives and thrives..

I searched github for recently added projects regarding meal planners and found a lot.. 
Among others this one:
https://github.com/holtzmak/Community-Meal-Planner

Which is only documentation.. and planning.. but thats important too..

I like this GO implementation and typescript frontend.. should we try and get some more contributors and work on your project here?

**Comment by chadweimer** [comment]
Thanks so much for the interest! At this moment in time, this is just a hobby project and a means for me to learn new technologies. You're the first person who's ever discovered it and expressed interest, which is quite exciting, but I'm not sure if I have the time to foster this into something more. It's an interesting thought though...

**Comment by KlavsKlavsen** [comment]
A free "github webpage" for the repo and inviting everyone to contribute.. could possibly attract developers.. and an updated readme to tell this as the first thing.. Community should be about many contributing - not you doing more :)

You've already made it very easy to spin up and run/develop on - and GO + typescript should definetely interest a lot of contributors IMHO
